---
title: "R Notebook"
output: html_notebook
---

No 1 (Limit)
$$ (A \cup B \cup C) $$
```{r}
U <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19)
B <- c(2,3,5,7,11,13,17,19)
C <- c(2,4,6,8,10,12,14,16,18)
A <- c(1:10)

union(union(A, B), C)
```

No 2 (Function)
$$ (a) f(x) = x^3 + x^2 - 6 \\
   (b) f(x) = -x^2 -6
$$
```{r}
f <- function(x) {
    result <- x^3 + x^2 - 6
    return(result)
}
plot(f)
```
```{r}
f <- function(x) {
    result <- -x^2 - 6
    return(result)
}
plot(f)
```

No 3
$$ Limit $$
```{r}
library(Ryacas)
yac_str("Limit(x,0) (x^4 - x^2)/(x^3 + x^2)*(sin(x)/x) + cos(x)")

yac_expr("Limit(x,0) (x^4 - x^2)/(x^3 + x^2)*(sin(x)/x) + cos(x)")
```

No 4
$$ Differentiation $$
```{r}
rule <- function(x){
  return((sin(x^2)/(x^2))*(x+1))
}
library(Ryacas)
yac_expr("D(x) (sin(x^2)/(x^2))*(x+1)")
```

No 5
$$ Integration $$
```{r}
integrand <- function(x) {
  return(x^2 * cos(x^3 + pi) * sin(x^3 + pi))
}

library(Ryacas)
x <- Sym("x")
Integrate(x^2 * cos(x^3 + pi) * sin(x^3 + pi), x)
```